### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by westhecool** [GhostyTongue/Roblox-Uncopylocked-Game-Version-Downloader#4]
The roblox server is denying access with error 409

**Comment by GhostyTongue** [comment]
it should work

**Comment by westhecool** [comment]
> it should work

It probably does the game was copy locked and I overlooked that.

**Comment by MiguelRubioJr** [comment]
makes sense

**Comment by GhostyTongue** [comment]
> 

yeah sorry its only for uncopylocked games
