### ISSUE TITLE
Keeps giving error codes 

### ISSUE THREAD

**Issue by Kbrighton32** [GhostyTongue/Roblox-Uncopylocked-Game-Version-Downloader#5]
I have tried countless times and all it does is give me error codes

**Comment by GhostyTongue** [comment]
share me a screenshot on discord:
**ghostytongue**

**Comment by GhostyTongue** [comment]
Also this might help
[](https://github.com/GhostyTongue/Roblox-Uncopylocked-Game-Version-Downloader/issues/4)
